### ISSUE TITLE
Wrong spin period?

### ISSUE THREAD

**Issue by ziotom78** [zonca/pico-simulations#12]
The spin period for PICO simulation is set to be 60 s, but I believe that TOAST expects this number in minutes (see [toast_satellite_sim.py](https://github.com/hpc4cmb/toast/blob/master/pipelines/toast_satellite_sim.py#L145)). If this is the case, the following lines of code are wrong:

- https://github.com/zonca/pico-simulations/blob/master/calibration_sim/pico_scanning.par#L4
- https://github.com/zonca/pico-simulations/blob/master/calibration_sim/pico_scanning.par#L8

**Comment by zonca** [comment]
sorry, I confirm this is an issue, it was actually there since the beginning, in fact if you check the Dipole and galacy plot in https://github.com/zonca/pico-simulations/issues/5#issuecomment-364922385 it has about 25 peaks in a day, which is consistent with a spin of 1 h...

I'll rerun the sims and update the issue once ready.

**Comment by ziotom78** [comment]
Yeah, sorry for not having discovered it before… I realized this was a problem while I was preparing the slides for my talk.
